# Netlify Configuration for AI Research & Book Generation Platform
# ===================================================================
# This file configures deployment settings for Netlify

[build]
  # Build command (not needed for static site, but can be used for preprocessing)
  command = "echo 'No build step required for static site'"
  
  # Directory to publish (root directory contains index.html)
  publish = "."
  
  # Ignore backend directory during deployment
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF backend/"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS headers (adjust as needed for your API)
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (optional)
[[redirects]]
  from = "/api/*"
  to = "https://your-api-gateway-url.execute-api.us-east-1.amazonaws.com/prod/:splat"
  status = 200
  force = false
  
  # Note: Replace the 'to' URL with your actual API Gateway endpoint
  # This creates a proxy to avoid CORS issues

# Environment variables (set in Netlify UI for security)
# AWS_REGION
# BEDROCK_MODEL_ID
# GROQ_API_KEY (if using serverless functions)

# Plugin configuration (optional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

# Build context for different branches
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  command = "echo 'Deploy preview'"

[context.branch-deploy]
  command = "echo 'Branch deploy'"
